# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5e90970007035d30cbbe8f51ca0ef2a68f9955dc24d3faab5ba3ab7614a396478469fc8e6f1e29014f4cafe5b5af63fac722011ade58d0b600832ee378d1cf7

test:
  secret_key_base: ce26841ad39e83c1d6485748157a5a106f3aac5b9aac073541b7f927ea62353e857b624507c4cca3a851c53e46e2921bf653cc4388d4d976adaaffe971180751

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
